hx20/hx30: Update github actions
BRANCH=fwk-hx20-hx30-4410
TEST=Action run stops failing, see below
BUG=upload-artifact v2 is deprecated and the action runs are failing.

Currently we're seeing the below failure:

> Error: This request has been automatically failed because it uses a
> deprecated version of `actions/upload-artifact: v2`. Learn more:
> https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Signed-off-by: Daniel Schaefer <dhs@frame.work>